baseURL = "https://hacknature.org/"
publishDir = "public"
canonifyurls = true
relativeURLs = true

title = "Stichting HackNature"
theme = "ajonp-hugo-ionic"
copyright = "Copyright 2023 - HackNature"

defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = false

[languages]
  [languages.nl]
    languageName = "Nederlands"
    title = "Stichting HackNature"
    weight = 1
  [languages.en]
    languageName = "Engels"
    title = "HackNature Foundation"
    weight = 2

[security]
  [security.funcs]
    getenv = ["^HUGO_","^WC_","^NODE_ENV"]
    