baseURL = "https://hacknature.org/"
title = "Stichting HackNature"
theme = "ajonp-hugo-ionic"
copyright = "Copyright 2021 - HackNature"

defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = false

[languages]
  [languages.nl]
    languageName = "Nederlands"
    title = "Stichting HackNature"
    weight = 1
  [languages.en]
    languageName = "Engels"
    title = "HackNature Foundation"
    weight = 2
