# This is a basic workflow to help you get started with Actions

name: Copy
on: 
    # Triggers the workflow on push or pull request events but only for the master branch
  push:
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: public/
        dst_path: /.
        dst_owner: hacknature
        dst_repo_name: websiteprod
        dst_branch: master
        src_branch: master
        src_wiki: false
        dst_wiki: false
        username: hacknature
        email: info@hacknature.org



     
