name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
        EXTERNAL_REPOSITORY: hacknature/website
        PUBLISH_BRANCH: master
        PUBLISH_DIR: /.
      with:
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}
